emailwiz.sh

Deleting all settings starting with o seems rather arbitrary, but I don't know the default configuration on Vultr, so could be warranted :) But I'll be bold and guess the `sed` command and the following lines are supposed to be related?

Fix typo in the deleting of `-o` flags

---

emailwiz.sh

default /etc/opendkim.conf has KeyTable appear in comment doco and example.
Shouldn't trigger the grep that checks whether this config has been applied.

prevent false detection of opendkim KeyTable config

---

emailwiz.sh

opendkim ignores the invalid SOCKET config line, causing smtpd mail send to fail.
```
$ sudo systemctl status opendkim
systemd[1]: Ignoring invalid environment assignment 'SOCKET=inet:8891@localhost
systemd[1]: ': /etc/sysconfig/opendkim
$ journalctl
postfix/submission/smtpd[17646]: fatal: host/service localhost/8891 not found: Device or resource busy
```

close quotation marks in opendkim socket config

---

emailwiz.sh

I've been using this script as a reference and noticed that mails from gmail to my server weren't being checked by SpamAssassin, but my own mail was.
Since incoming mail comes from port 25, it might make more sense to put spamassassin on port 25 postfix service instead of 587 and 465 (through which outgoing mail is received e.g. with `msmtp`).

Use spamassassin on port 25 only

---

emailwiz.sh

The main command for generating DKIM keys (`opendkim`) wasn't installed with just the `opendkim` package.  Added a fix so it would be installed should it not be there the first time `apt` is ran.

Make sure the opendkim tools are installed

---

emailwiz.sh

This prevents sent emails from being marked as insecure in Gmail.

Fix TLS encrypted emails to Gmail

---

emailwiz.sh

- Create user vmail, if not present.
- Add 'login' option in dovecot to be able to send emails fro mutt.
Although I just noticed, that it is possible to set smtp_authenticators to plain in muttrc. This way including login in dovecot.conf ist not necessary.
- Add dovecot-sieve. Otherwise sievec would be missing.

Added relaxed option for DKIM.

---

README.md

Technically Postfix is responsible for sending *and* receiving mail between *your server and other SMTP servers* (Mail Transfer Agents). Dovecot is only so you can view your mail in email clients on your computer instead of server, which is not really *receiving*. You can have a perfectly functional email system with no IMAP/POP server at all, you'd just have to read your email over SSH or whatever

Change Dovecot/Postfix definition

---

emailwiz.sh

I noticed the following line (line 75) in your script:
`postconf -e "smtp_tls_CAfile=$certdir/cert.pem"`
According to the [docs](http://www.postfix.org/postconf.5.html#smtp_tls_CAfile) this parameter specifies the CA file for the smtp client. If I understand this correctly, this means that with this setting in place you are effectively refusing connections from servers which don't use letsencrypt as CA.
I propose to remove the line in it's entirety, as the CA cert is already contained in the `fullchain.pem` cert.

remove smtp_tls_CAfile from postfix main.cf

---

emailwiz.sh

According to the [Dovecot wiki](https://wiki.dovecot.org/SSL/DovecotConfiguration):-
> From version 2.3, you must specify path to DH parameters file using:
> ssl_dh=</path/to/dh.pem"
> 
This actually threw an error something along the lines of `imap-login: Error: Failed to initialize SSL`
when I updated my VPS to Debian Buster.

Minor change for dovecot.conf to work on v2.3

---

emailwiz.sh

Increase security of TLS connections by enforcing TLS1.2 and disabling weak ciphersuites.

Enforce TLS1.2 connections

---

emailwiz.sh

Added fixes for setting up an email server on a custom subdomain (other than "mail")
- Fixes entry in DKIM signing table to use correct selector and key filename
- Fixes `pval` variable to source TXT record from correct file
- Added optional env var for specifying a custom subdomain name

Fixes for custom subdomain names

---

emailwiz.sh

After following your youtube video completely on fresh install of Debian 10 hosted on vultr, i could not get DKIM to pass with appmaildev.com.
After checking systemctl I've seen:
`
systemd[1]: Starting OpenDKIM DomainKeys Identified Mail (DKIM) Milter...
systemd[1]: opendkim.service: Can't open PID file /var/run/opendkim/opendkim.pid (yet?) after start: No such file or directory
opendkim[8226]: OpenDKIM Filter v2.11.0 starting (args: -x /etc/opendkim.conf)
systemd[1]: opendkim.service: Start operation timed out. Terminating.
`
After a long internet searching i noticed that a lot of people experienced the same issue. After trying a few fixes with no avail, i stumbled upon [this](https://serverfault.com/a/847442), which solves the issue perfectly with a script that's provided with a …

Fix: Opendkim won't start: can't open PID file?

---

emailwiz.sh

This is a fix for the issue #178 regarding IP address leakage.
I decided to open this pull request because the issue opener hasn't opened one already, and this issue thread seems to have been dormant for some time.
These changes applied to my current email server, and I have not encountered issues yet (Running Debian 11 Stable).
I have double checked the `postconf` man page too, just to make sure that want was said in the source comments was accurate and so that I wasn't doing something stupid.

Fix: #178 leakage of public IP addresses in sent emails

---

emailwiz.sh

Prevents some weird permission errors ala #195 if the user has a custom `umask`
Closes #195

Reset umask to 0022 at beginning of install

---

emailwiz.sh

I had a problem inserting the spf1 entry on my DNS provider. It couldn't parse the @. Just inserting it with my domain as key worked, so I guess @ is just an alias for 'current domain'. Therefore wouldn't be using the domain instead of @ in the script be more general?

use domain instead of @

---

emailwiz.sh

By default the deploy hook runs when any certificate is renewed, with these changes the hook only runs when the mail cert is renewed

Only call deploy hook when mail cert is renewed

---

emailwiz.sh

Fixes #237 
It works, but note that I have only tested this using my setup where this script is partially run in docker, so I haven't tested this using the vanilla script.

Resolve "Anyone can send mails from a local user as long as the recipient is another local user"

---

emailwiz.sh

Unless you intend to interpolate, you should never use double-quotes. In this instance, it was actually impactful -- `$myhostname` and `$mydomain` were meant to be left as-is, referring to those Postfix config parameters, but were accidentally interpolated and subsequently generating nonsense (but not fatal) configuration.
The generated config would look like this:
`mydestination = , , mail, localhost.localdomain, localhost, localhost.`
instead of:
`mydestination = $myhostname, $mydomain, mail, localhost.localdomain, localhost, localhost.$mydomain`

Use single-quotes to prevent interpolation when configuring Postfix

---

emailwiz.sh

This commits checks for /etc/default/spamassassin. If it exists, it's passed through sed to modify the CRON variable as usual, and spamassassin.service is enabled and restarted.
If /etc/default/spamassassin does not exist, but /etc/default/spamd exists, we modify /etc/default/spamd instead, and restart and enable spamd.service.
This has to be done because Debian 12 introduced this breaking change: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020859
This commit fixes #282

Make it work with Debian 12: spamassassin -> spamd

---

emailwiz.sh

> DNS records that point at least your domain's mail. subdomain to your server's IP (IPv4 **and** IPv6). This is required on initial run for certbot to get an SSL certificate for your mail. subdomain.
Someone can forget to setup their AAAA record and the script will still appear to work (certbot doesn't need ipv6). This pr adds a safeguard to include ipv4 and ipv6 into the spf record. Martin [found](https://github.com/LukeSmithxyz/landchad/pull/298) by adding it he could send to gmail even without the AAAA record.
I guess what's happening here is some people are not watching the video tutorial so they skip over adding AAAA record since it's not explicitly stated to do so in the text based guides.

Add safeguards to script

---

emailwiz.sh

Following the recent [disclosure of the SMTP smuggling 0-day vulnerability in Postfix](https://www.postfix.org/smtp-smuggling.html), this pull request applies the suggested short-term workaround from the linked blog post. This fix (currently) only works with Postfix 3.7.(>=6), which is currently packaged by Debian bookworm (i.e., no Ubuntu, no Debian bullseye) so it might be beneficial to also add a notice in the `README.md` for manual intervention.

Short-term workaround to prevent SMTP smuggling

---

emailwiz.sh

This makes the user more descriptive of potential other use cases. One example would be the mailto field in MTA-STS records

feat: turn user "dmarc" into "postmaster" for more generic use cases

---

emailwiz.sh

-- the change to the apt-get install part at the beginning forces an uninstall and purge of configs. This means that if you re-run the script it will "reset" the install to default state by deleting packages and configs and re-installing and re-generating the configs.
--I turned some hardcoded settings into options that can be set in the variables at the top of the script (for convenience). The default behavior is the same as before. allow_suboptimal_ciphers="yes" #yes no
mailbox_format="maildir" # maildir sdbox
allowed_protocols=" imap pop3 "  #imap pop3
--added a setting "selfsigned="no" # yes no" to choose between  "let's get a cert from letsencrypt" and "create self-signed cert that lasts 100 years", and added the logic to generate the certs and whatnot. My usecase is for an …

now it can make self-signed certs, turn some settings into options

---

README.md

since you merged the PR about the self-signed certificate, this adds documentation in the Readme to know that this feature exists and how to use it

Add instructions for self-signed certs

---

emailwiz.sh

reject_sender_login_mismatch in smptd_sender_restrictions will never be matched, the mail is always permitted by permit_sasl_authenticated first.

Swap restriction order in main.cf to catch sender login mismatch
